
version: "3.7"

services:
  app:
    build:
      context: .
      target: develop
    image: tikhoplav/wordify:dev
    volumes:
      - ./src:/src
      - ./pkg:/go/pkg
      - ./data:/data
    ports:
      - 80:80
    command: go test